# Generated by Django 3.0.5 on 2020-05-17 09:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20200502_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=128),
        ),
    ]
