# Generated by Django 3.0.6 on 2020-06-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200517_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('None', 'None'), ('India', 'India')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('none', 'none'), ('Assam', 'Assam'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Tamil Nadu', 'Tamil Nadu'), ('Karnataka', 'Karnataka'), ('Goa', 'Goa'), ('Rajasthan', 'Rajasthan'), ('Bihar', 'Bihar')], max_length=128, null=True),
        ),
    ]
